---

- hosts: all
  become: true
  pre_tasks:

  - name: Installing update and upgrade (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Installing update and upgrade (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:

  - name: Installing ntp, mssql
    apt:
      name:
        - ntp
        - mysql-server
      state: latest
      update_cache: yes
