---

- hosts: all
  become: true
  pre_tasks:

  - name: Installing updates and upgrade (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Installing update and upgrade (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: web_servers
  become: true
  tasks:

  - name: Installing Message Queue and Memcached
    apt:
      name:
        - rabbitmq-server
        - memcached
      state: latest
      update_cache: yes
